### ISSUE TITLE
Error after new update

### ISSUE THREAD

**Issue by kishanio** [dbtk/schema-loader#7]
Now when i try to load scheme it gives me following error 

 [Doctrine\DBAL\Schema\SchemaException]
The column '<column_name>' on table '<table_name>' already exists.

It worked fine until version 1.0.5

**Comment by joostfaassen** [comment]
Hey @kishanio, sorry about that!
I've just tagged v1.1.2, which should solve this problem. Can you composer update and try again?

@igormukhingmailcom i've changed the xpath on 
https://github.com/dbtk/schema-loader/blob/cad35edcdb56a0208086ffa966b6989223dbce6c/src/Loader/XmlLoader.php#L50
Can you verify if this is the best way to do it?

Cheers!
Joost
